export const MICROSERVICES_CLIENTS = {
      USERS_SERVICE: "USERS_SERVICE",
      ORDERS_SERVICE: "ORDERS_SERVICE",
      PRODUCTS_SERVICE: "PRODUCTS_SERVICE",
      PAYMENTS_SERVICE: "PAYMENTS_SERVICE",
      AUTH_SERVICE: "AUTH_SERVICE"
}